drop table if exists
    wheels_size,
    wheels,
    bodies_types,
    bodies,
    cars
    cascade;

create table if not exists wheels_size
(
    id        bigint generated by default as identity primary key not null,
    size_name varchar(50)                                         not null
--маркировка трехбуквенная, но на случай если будут более длинные названия размеров оставлено увеличенное поле
);

create table if not exists wheels
(
    id             bigint generated by default as identity primary key not null,
    stock          integer                                             not null,
    wheels_size_id bigint references wheels_size (id)
);

create table if not exists bodies_type
(
    id        bigint generated by default as identity primary key not null,
    type_name varchar(255)                                        not null
);

create table if not exists bodies
(
    id    bigint generated by default as identity primary key not null,
    stock integer                                             not null,
    type_id  bigint references bodies_type (id)                 not null
);

create table if not exists cars
(
    id            bigint generated by default as identity primary key not null,
    name          varchar(255)                                        not null,
    wheels_id     bigint references wheels (id)                       not null,
    wheels_amount integer                                             not null,
    body_id     bigint references bodies (id)                       not null
);